# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.python import arith_pb2 as arith__pb2


class ArithStub(object):
    """定义算术服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.XiangJia = channel.unary_unary(
                '/mgolang.Arith/XiangJia',
                request_serializer=arith__pb2.ArithRequest.SerializeToString,
                response_deserializer=arith__pb2.ArithResponse.FromString,
                )
        self.XiangJian = channel.unary_unary(
                '/mgolang.Arith/XiangJian',
                request_serializer=arith__pb2.ArithRequest.SerializeToString,
                response_deserializer=arith__pb2.ArithResponse.FromString,
                )


class ArithServicer(object):
    """定义算术服务
    """

    def XiangJia(self, request, context):
        """定义相加方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def XiangJian(self, request, context):
        """定义相减方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArithServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'XiangJia': grpc.unary_unary_rpc_method_handler(
                    servicer.XiangJia,
                    request_deserializer=arith__pb2.ArithRequest.FromString,
                    response_serializer=arith__pb2.ArithResponse.SerializeToString,
            ),
            'XiangJian': grpc.unary_unary_rpc_method_handler(
                    servicer.XiangJian,
                    request_deserializer=arith__pb2.ArithRequest.FromString,
                    response_serializer=arith__pb2.ArithResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mgolang.Arith', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Arith(object):
    """定义算术服务
    """

    @staticmethod
    def XiangJia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mgolang.Arith/XiangJia',
            arith__pb2.ArithRequest.SerializeToString,
            arith__pb2.ArithResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def XiangJian(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mgolang.Arith/XiangJian',
            arith__pb2.ArithRequest.SerializeToString,
            arith__pb2.ArithResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
